# Generated by Django 4.2.9 on 2024-02-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="liked_by",),
        migrations.AddField(
            model_name="post", name="likes", field=models.IntegerField(default=0),
        ),
    ]
