# Generated by Django 5.0.1 on 2024-03-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='comments',
            name='liked_by',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
