# Generated by Django 5.0.1 on 2024-03-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
