# Generated by Django 5.0.1 on 2024-03-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255, unique=True)),
                ('server_url', models.URLField(max_length=1024)),
                ('incoming_username', models.CharField(max_length=255)),
                ('incoming_password', models.CharField(max_length=255)),
                ('outgoing_username', models.CharField(max_length=255)),
                ('outgoing_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Nodes',
        ),
    ]
