# Generated by Django 5.0.1 on 2024-03-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_type',
            new_name='contentType',
        ),
    ]
