# Generated by Django 5.0.2 on 2024-03-08 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followers",
            name="author_to_follow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
