# Generated by Django 5.0.1 on 2024-03-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(default='http://localhost:8000', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://localhost:8000'),
        ),
    ]
