# Generated by Django 5.0.2 on 2024-03-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="inbox", name="comment",),
        migrations.RemoveField(model_name="inbox", name="liked",),
        migrations.RemoveField(model_name="inbox", name="messages",),
        migrations.RemoveField(model_name="inbox", name="post",),
        migrations.AddField(
            model_name="inbox",
            name="content",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
