# Generated by Django 5.0.1 on 2024-03-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubLastUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_time', models.DateTimeField()),
            ],
        ),
    ]
