# Generated by Django 5.0.2 on 2024-03-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0002_remove_inbox_comment_remove_inbox_liked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")], max_length=10
            ),
        ),
    ]
