# Generated by Django 5.0.1 on 2024-03-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0002_rename_content_type_post_contenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_counts',
            new_name='count',
        ),
    ]
