# Generated by Django 5.0.1 on 2024-03-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0002_servercredentials_delete_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_objects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
