# Generated by Django 5.0.1 on 2024-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0002_alter_post_origin_alter_post_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True, default='https://i.imgur.com/WxNkK7J.png'),
        ),
    ]
