# Generated by Django 5.0.1 on 2024-03-20 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0002_githublastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githublastupdate',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
