# Generated by Django 4.2.9 on 2024-02-21 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0002_remove_post_liked_by_post_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="likes",),
        migrations.AddField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
