# Generated by Django 5.0.1 on 2024-03-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0002_alter_user_user_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="user_email",),
    ]
