# Generated by Django 5.0.1 on 2024-03-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0003_alter_githublastupdate_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True, default='https://imgur.com/a/i9xknax'),
        ),
    ]
