# Generated by Django 5.0.2 on 2024-03-08 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0003_inbox"),
    ]

    operations = [
        migrations.RemoveField(model_name="inbox", name="items",),
        migrations.AddField(
            model_name="inbox",
            name="messages",
            field=models.TextField(blank=True, default="This is a message", null=True),
        ),
        migrations.AddField(
            model_name="inbox",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webwizardsapp.post",
            ),
        ),
    ]
