# Generated by Django 5.0.1 on 2024-03-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0003_rename_comment_counts_post_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='created',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='user',
            name='host',
            field=models.CharField(default='http://localhost:8000', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(default='http://localhost:8000', max_length=500),
        ),
    ]
