# Generated by Django 5.0.1 on 2024-03-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0003_alter_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.CharField(default='http://localhost:8000/', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(default='http://localhost:8000/', max_length=500),
        ),
    ]
