# Generated by Django 5.0.1 on 2024-02-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0003_remove_post_likes_post_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
