# Generated by Django 5.0.1 on 2024-02-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0004_post_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_data',
        ),
    ]
