# Generated by Django 5.0.2 on 2024-03-11 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0004_remove_inbox_items_inbox_messages_inbox_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webwizardsapp.comments",
            ),
        ),
        migrations.AddField(
            model_name="inbox",
            name="liked",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
