# Generated by Django 5.0.2 on 2024-03-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0005_inbox_comment_inbox_liked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="published", new_name="created",
        ),
    ]
