# Generated by Django 5.0.1 on 2024-02-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0005_alter_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://imgur.com/a/i9xknax'),
        ),
    ]
