# Generated by Django 5.0.1 on 2024-03-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0005_followerlist_delete_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerlist',
            name='followers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted')], max_length=10),
        ),
    ]
