# Generated by Django 5.0.1 on 2024-03-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0006_alter_followerlist_followers_alter_post_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Comment_counts',
            new_name='comment_counts',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(default='text/plain', max_length=200),
        ),
    ]
