# Generated by Django 5.0.2 on 2024-03-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webwizardsapp", "0006_rename_published_post_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="created", new_name="published",
        ),
    ]
