# Generated by Django 5.0.1 on 2024-03-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0010_remove_post_liked_by_post_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
