# Generated by Django 5.0.1 on 2024-03-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0011_alter_post_liked_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeditem',
            unique_together=set(),
        ),
    ]
