# Generated by Django 5.0.1 on 2024-03-18 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0012_alter_likeditem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeditem',
            name='item',
        ),
        migrations.AddField(
            model_name='likeditem',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='likeditem',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
