# Generated by Django 5.0.1 on 2024-03-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webwizardsapp', '0013_remove_likeditem_item_likeditem_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerlist',
            name='followers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
